import React, { useMemo, useState } from 'react';
import { Copy, Download, ExternalLink, Mail, Pencil, Plus, Trash2, Users } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { AppIconImage } from '../common/AppIconImage';
import { CampaignImageUploader } from '../common/CampaignImageUploader';
import { copyTesterGmailsToClipboard, exportTestersToCsv } from '../../utils/exportTesters';
import type { AppCampaign, TesterStatus } from '../../types';

const states: TesterStatus[] = ['pending', 'accepted', 'waiting_for_whitelisting', 'ready_to_join', 'joined', 'active', 'completed', 'inactive', 'rejected'];
type Form = { name: string; slug: string; developerName: string; platform: 'android' | 'ios'; testType: AppCampaign['testType']; category: AppCampaign['category']; tagline: string; description: string; campaignGoal: string; testingInstructions: string; durationDays: number; requiredTestersCount: number; rewardTitle: string; rewardValue: string; testUrl: string; iconUrl: string; status: AppCampaign['status'] };
const blank = (): Form => ({ name: '', slug: '', developerName: 'TestFlow', platform: 'android', testType: 'google_play_closed', category: 'tools', tagline: '', description: '', campaignGoal: '', testingInstructions: '', durationDays: 14, requiredTestersCount: 20, rewardTitle: '', rewardValue: '', testUrl: '', iconUrl: '', status: 'draft' });
const buildCampaign = (form: Form) => ({ ...form, screenshots: [], developerId: '', version: '1.0.0', targetCountries: [], targetDevices: [], minOsVersion: '', startDate: new Date().toISOString().slice(0, 10), endDate: '', tasks: [], reward: form.rewardTitle ? { type: 'cash' as const, title: form.rewardTitle, value: form.rewardValue, description: '' } : undefined });

export const AdminDashboard: React.FC = () => {
  const app = useApp();
  const [form, setForm] = useState<Form>(blank);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [uploading, setUploading] = useState(false);
  const [campaignId, setCampaignId] = useState('all');
  const [filterStatus, setFilterStatus] = useState('all');
  const [platform, setPlatform] = useState('all');
  const [selected, setSelected] = useState<string[]>([]);
  const shown = useMemo(() => app.applications.filter((item) => (campaignId === 'all' || item.campaignId === campaignId) && (filterStatus === 'all' || item.status === filterStatus) && (platform === 'all' || item.osType === platform)), [app.applications, campaignId, filterStatus, platform]);
  const field = <K extends keyof Form>(key: K, value: Form[K]) => setForm((current) => ({ ...current, [key]: value }));
  const reset = () => { setForm(blank()); setEditingId(null); };
  const selectedApps = shown.filter((item) => selected.includes(item.id));

  const edit = (campaign: AppCampaign) => {
    setEditingId(campaign.id);
    setForm({ name: campaign.name, slug: campaign.slug, developerName: campaign.developerName, platform: campaign.platform === 'ios' ? 'ios' : 'android', testType: campaign.testType === 'testflight' ? 'testflight' : 'google_play_closed', category: campaign.category, tagline: campaign.tagline, description: campaign.description, campaignGoal: campaign.campaignGoal || '', testingInstructions: campaign.testingInstructions, durationDays: campaign.durationDays, requiredTestersCount: campaign.requiredTestersCount, rewardTitle: campaign.rewardTitle || campaign.reward?.title || '', rewardValue: campaign.rewardValue || campaign.reward?.value || '', testUrl: campaign.testUrl || '', iconUrl: campaign.iconUrl || '', status: campaign.status });
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };
  const save = async (event: React.FormEvent) => {
    event.preventDefault();
    if (uploading) return;
    try {
      if (editingId) {
        if (!await app.updateCampaign(editingId, buildCampaign(form))) return;
        app.showToast('تم حفظ تعديلات الحملة.');
      } else {
        await app.addCampaign(buildCampaign(form));
        app.showToast('تم إنشاء الحملة.');
      }
      reset();
    } catch { app.showToast('تعذر حفظ الحملة.', 'error'); }
  };
  const csv = (mode: 'full' | 'gmail_only', list = shown) => list.length ? exportTestersToCsv({ applications: list, campaigns: app.campaigns, mode }) : app.showToast('لا توجد طلبات مختبرين.', 'warning');
  const approvalMessage = (name: string) => `مرحباً ${name}،\n\nتمت الموافقة على طلب انضمامك كمطور في TestFlow.\nيمكنك الآن تسجيل الدخول بالحساب نفسه وإدارة حملاتك ومختبريك.\n\nرابط المنصة: ${window.location.origin}\n\nمع تحيات فريق TestFlow`;

  return <main className="max-w-7xl mx-auto space-y-6 p-4 sm:p-6" dir="rtl">
    <header className="rounded-2xl bg-slate-950 p-6 text-white"><h1 className="text-2xl font-black">لوحة إدارة TestFlow</h1><p className="text-slate-300">الحملات، المطورون، وطلبات المختبرين</p></header>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[['الحملات', app.campaigns.length], ['المختبرون', app.applications.length], ['طلبات مختبرين معلقة', app.applications.filter((item) => item.status === 'pending').length], ['طلبات مطورين معلقة', app.developers.filter((item) => item.status === 'pending_approval').length], ['الحملات النشطة', app.campaigns.filter((item) => item.status === 'active').length]].map(([label, count]) => <div key={String(label)} className="rounded-xl border bg-white p-4"><small>{label}</small><b className="block text-2xl">{count}</b></div>)}</div>
    <section className="rounded-2xl border bg-white p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-black">{editingId ? 'تعديل الحملة' : 'إنشاء حملة'}</h2>{editingId && <button type="button" onClick={reset} className="text-sm text-slate-600">إلغاء التعديل</button>}</div><form onSubmit={save} className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
      <input required placeholder="اسم التطبيق" value={form.name} onChange={(e) => field('name', e.target.value)} className="rounded-lg border p-2" /><input required placeholder="slug مثل rawnak" value={form.slug} onChange={(e) => field('slug', e.target.value)} className="rounded-lg border p-2" /><input placeholder="اسم المطور / الجهة" value={form.developerName} onChange={(e) => field('developerName', e.target.value)} className="rounded-lg border p-2" />
      <select value={form.platform} onChange={(e) => field('platform', e.target.value as 'android' | 'ios')} className="rounded-lg border p-2"><option value="android">Android</option><option value="ios">iOS</option></select><select value={form.testType} onChange={(e) => field('testType', e.target.value as AppCampaign['testType'])} className="rounded-lg border p-2"><option value="google_play_closed">Google Play Closed Testing</option><option value="testflight">TestFlight</option></select><select value={form.category} onChange={(e) => field('category', e.target.value as AppCampaign['category'])} className="rounded-lg border p-2">{['tools', 'productivity', 'finance', 'health', 'social', 'games', 'education'].map((item) => <option key={item}>{item}</option>)}</select>
      <input placeholder="وصف قصير" value={form.tagline} onChange={(e) => field('tagline', e.target.value)} className="rounded-lg border p-2" /><input placeholder="هدف الحملة" value={form.campaignGoal} onChange={(e) => field('campaignGoal', e.target.value)} className="rounded-lg border p-2" /><input placeholder="عنوان المكافأة" value={form.rewardTitle} onChange={(e) => field('rewardTitle', e.target.value)} className="rounded-lg border p-2" />
      <input placeholder="قيمة المكافأة" value={form.rewardValue} onChange={(e) => field('rewardValue', e.target.value)} className="rounded-lg border p-2" /><input required type="url" placeholder="رابط الاختبار الخاص" value={form.testUrl} onChange={(e) => field('testUrl', e.target.value)} className="rounded-lg border p-2" /><CampaignImageUploader value={form.iconUrl} appName={form.name} category={form.category} onChange={(url) => field('iconUrl', url)} onUploadStateChange={setUploading} />
      <input type="number" min="1" aria-label="مدة الاختبار بالأيام" value={form.durationDays} onChange={(e) => field('durationDays', Number(e.target.value))} className="rounded-lg border p-2" /><input type="number" min="1" aria-label="عدد المختبرين المطلوب" value={form.requiredTestersCount} onChange={(e) => field('requiredTestersCount', Number(e.target.value))} className="rounded-lg border p-2" /><select value={form.status} onChange={(e) => field('status', e.target.value as AppCampaign['status'])} className="rounded-lg border p-2">{['draft', 'active', 'paused', 'completed'].map((item) => <option key={item}>{item}</option>)}</select>
      <textarea placeholder="الوصف الكامل" value={form.description} onChange={(e) => field('description', e.target.value)} className="min-h-24 rounded-lg border p-2 md:col-span-2" /><textarea placeholder="تعليمات الاختبار" value={form.testingInstructions} onChange={(e) => field('testingInstructions', e.target.value)} className="min-h-24 rounded-lg border p-2 md:col-span-2" />
      <button disabled={uploading} className="rounded-lg bg-blue-600 p-3 font-bold text-white disabled:cursor-not-allowed disabled:opacity-60 xl:col-span-3"><Plus className="inline h-4 w-4" /> {uploading ? 'انتظر حتى يكتمل رفع الصورة' : editingId ? 'حفظ التعديل' : 'إنشاء الحملة'}</button>
    </form></section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="mb-3 text-lg font-black">طلبات المطورين</h2>{app.developers.map((developer) => <div key={developer.id} className="flex flex-col justify-between gap-2 border-b py-3 md:flex-row"><span><b>{developer.name}</b> · {developer.email} · {developer.companyName} · {developer.status}<small className="block text-slate-500">{developer.bio || 'لا توجد نبذة'} · {developer.submittedAt}</small></span><span className="flex gap-3 text-sm">{developer.status === 'pending_approval' && <><button className="text-emerald-700" onClick={() => app.updateDeveloperStatus(developer.id, 'approved')}>قبول</button><button className="text-rose-700" onClick={() => app.updateDeveloperStatus(developer.id, 'rejected')}>رفض</button></>}{developer.status === 'approved' && <><a className="text-blue-700" href={`mailto:${developer.email}?subject=${encodeURIComponent('تم قبول طلبك كمطور في TestFlow')}&body=${encodeURIComponent(approvalMessage(developer.name))}`}><Mail className="inline h-4 w-4" /> إرسال بريد</a><button onClick={() => navigator.clipboard.writeText(approvalMessage(developer.name)).then(() => app.showToast('تم نسخ رسالة الموافقة.'))}><Copy className="inline h-4 w-4" /> نسخ رسالة</button></>}</span></div>)}</section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="mb-3 text-lg font-black">الحملات</h2>{app.campaigns.map((campaign) => <div key={campaign.id} className="flex flex-col justify-between gap-3 border-b py-3 md:flex-row"><div className="flex items-center gap-3"><AppIconImage src={campaign.iconUrl} appName={campaign.name} category={campaign.category} className="h-11 w-11 rounded-xl" /><span><b>{campaign.name}</b> · /{campaign.slug} · {campaign.platform} · {campaign.status}<small className="block text-slate-500">{app.applications.filter((item) => item.campaignId === campaign.id).length}/{campaign.requiredTestersCount} مختبر</small></span></div><span className="flex flex-wrap gap-3 text-sm"><a target="_blank" rel="noreferrer" href={`/campaign/${campaign.slug}`}><ExternalLink className="inline h-4 w-4" /> العامة</a><button onClick={() => setCampaignId(campaign.id)}><Users className="inline h-4 w-4" /> المختبرون</button><button onClick={() => edit(campaign)}><Pencil className="inline h-4 w-4" /> تعديل</button><button onClick={() => void app.updateCampaign(campaign.id, { status: campaign.status === 'active' ? 'paused' : 'active' })}>{campaign.status === 'active' ? 'إيقاف' : 'تفعيل'}</button><button className="text-rose-700" onClick={() => void app.removeCampaign(campaign.id)}><Trash2 className="inline h-4 w-4" /> حذف</button></span></div>)}</section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="mb-3 text-lg font-black">طلبات المختبرين</h2><div className="mb-3 flex flex-wrap gap-2"><select value={campaignId} onChange={(e) => setCampaignId(e.target.value)} className="rounded border p-2"><option value="all">كل الحملات</option>{app.campaigns.map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.name}</option>)}</select><select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)} className="rounded border p-2"><option value="all">كل الحالات</option>{states.map((item) => <option key={item}>{item}</option>)}</select><select value={platform} onChange={(e) => setPlatform(e.target.value)} className="rounded border p-2"><option value="all">Android/iOS</option><option value="android">Android</option><option value="ios">iOS</option></select><button onClick={() => csv('full', app.applications)} className="rounded border p-2"><Download className="inline h-4 w-4" /> All CSV</button><button onClick={() => csv('full')} className="rounded border p-2">Filtered CSV</button><button onClick={() => csv('full', selectedApps)} className="rounded border p-2">Selected CSV</button><button onClick={() => csv('gmail_only')} className="rounded border p-2">Gmail CSV</button><button onClick={() => copyTesterGmailsToClipboard(shown).then((count) => app.showToast(`تم نسخ ${count} بريد.`))} className="rounded border p-2"><Copy className="inline h-4 w-4" /> نسخ Gmail</button></div><div className="overflow-auto"><table className="w-full text-xs"><thead><tr className="border-b text-right"><th></th><th>الاسم</th><th>Gmail</th><th>Play/Apple</th><th>التطبيق</th><th>الجهاز</th><th>النظام</th><th>الإصدار</th><th>الدولة</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>{shown.map((application) => <tr key={application.id} className="border-b"><td><input type="checkbox" checked={selected.includes(application.id)} onChange={() => setSelected((items) => items.includes(application.id) ? items.filter((id) => id !== application.id) : [...items, application.id])} /></td><td>{application.testerName}</td><td>{application.testerEmail}</td><td>{application.googlePlayEmail}</td><td>{app.campaigns.find((campaign) => campaign.id === application.campaignId)?.name}</td><td>{application.deviceModel}</td><td>{application.osType}</td><td>{application.osVersion}</td><td>{application.testerCountry}</td><td><select value={application.status} onChange={(e) => app.updateApplicationStatus(application.id, e.target.value as TesterStatus)}>{states.map((item) => <option key={item}>{item}</option>)}</select></td><td>{application.appliedAt}</td></tr>)}</tbody></table></div></section>
  </main>;
};
