import React, { useMemo, useState } from 'react';
import { Copy, Download, ExternalLink, Mail, Plus, Trash2, Users } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { copyTesterGmailsToClipboard, exportTestersToCsv } from '../../utils/exportTesters';
import type { AppCampaign, TesterStatus } from '../../types';

const applicationStatuses: TesterStatus[] = ['pending','accepted','waiting_for_whitelisting','ready_to_join','joined','active','completed','inactive','rejected'];
const fresh = () => ({ name:'',slug:'',developerName:'TestFlow',platform:'android' as 'android'|'ios',testType:'google_play_closed' as AppCampaign['testType'],category:'tools' as AppCampaign['category'],tagline:'',description:'',campaignGoal:'',testingInstructions:'',durationDays:14,requiredTestersCount:20,rewardTitle:'',rewardValue:'',testUrl:'',iconUrl:'',status:'draft' as AppCampaign['status'] });

export const AdminDashboard: React.FC = () => {
  const app = useApp(); const [form,setForm] = useState(fresh); const [campaignId,setCampaignId] = useState('all'); const [status,setStatus] = useState('all'); const [platform,setPlatform] = useState('all'); const [selected,setSelected] = useState<string[]>([]);
  const shown = useMemo(() => app.applications.filter((a) => (campaignId==='all'||a.campaignId===campaignId) && (status==='all'||a.status===status) && (platform==='all'||a.osType===platform)), [app.applications,campaignId,status,platform]);
  const selectedApps = shown.filter((a) => selected.includes(a.id));
  const csv = (mode:'full'|'gmail_only', list = shown) => list.length ? exportTestersToCsv({applications:list,campaigns:app.campaigns,mode}) : app.showToast('لا توجد طلبات مختبرين.', 'warning');
  const create = async (e:React.FormEvent) => { e.preventDefault(); try { await app.addCampaign({ ...form, screenshots:[],developerId:'',version:'1.0.0',targetCountries:[],targetDevices:[],minOsVersion:'',startDate:new Date().toISOString().slice(0,10),endDate:'',tasks:[],reward:form.rewardTitle?{type:'cash',title:form.rewardTitle,value:form.rewardValue,description:''}:undefined }); setForm(fresh()); app.showToast('تم إنشاء الحملة.'); } catch { app.showToast('تعذر إنشاء الحملة.', 'error'); } };
  const emailText = (name:string) => 'مرحباً '+name+'،\n\nتمت الموافقة على طلب انضمامك كمطور في TestFlow.\nيمكنك الآن تسجيل الدخول بالحساب نفسه وإدارة حملاتك ومختبريك.\n\nرابط المنصة: '+window.location.origin+'\n\nمع تحيات فريق TestFlow';
  return <main className="max-w-7xl mx-auto p-4 sm:p-6 space-y-6" dir="rtl">
    <header className="bg-slate-950 text-white rounded-2xl p-6"><h1 className="text-2xl font-black">لوحة إدارة TestFlow</h1><p className="text-slate-300">الحملات، المطورون، وطلبات المختبرين</p></header>
    <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[['الحملات',app.campaigns.length],['المختبرون',app.applications.length],['المعلقة',app.applications.filter(a=>a.status==='pending').length],['طلبات المطورين',app.developers.filter(d=>d.status==='pending_approval').length],['النشطة',app.campaigns.filter(c=>c.status==='active').length]].map((x)=><div key={String(x[0])} className="border bg-white rounded-xl p-4"><small>{x[0]}</small><b className="block text-2xl">{x[1]}</b></div>)}</div>
    <section className="border rounded-2xl bg-white p-5"><h2 className="font-black text-lg mb-4">إنشاء حملة</h2><form onSubmit={create} className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">
      <input required placeholder="اسم التطبيق" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="border rounded-lg p-2"/><input required placeholder="slug مثل rawnak" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} className="border rounded-lg p-2"/><input placeholder="اسم المطور / الجهة" value={form.developerName} onChange={e=>setForm({...form,developerName:e.target.value})} className="border rounded-lg p-2"/>
      <select value={form.platform} onChange={e=>setForm({...form,platform:e.target.value as 'android'|'ios'})} className="border rounded-lg p-2"><option value="android">Android</option><option value="ios">iOS</option></select><select value={form.testType} onChange={e=>setForm({...form,testType:e.target.value as AppCampaign['testType']})} className="border rounded-lg p-2"><option value="google_play_closed">Google Play Closed Testing</option><option value="testflight">TestFlight</option></select><select value={form.category} onChange={e=>setForm({...form,category:e.target.value as AppCampaign['category']})} className="border rounded-lg p-2">{['tools','productivity','finance','health','social','games','education'].map(x=><option key={x}>{x}</option>)}</select>
      <input placeholder="وصف قصير" value={form.tagline} onChange={e=>setForm({...form,tagline:e.target.value})} className="border rounded-lg p-2"/><input placeholder="هدف الحملة" value={form.campaignGoal} onChange={e=>setForm({...form,campaignGoal:e.target.value})} className="border rounded-lg p-2"/><input placeholder="عنوان المكافأة" value={form.rewardTitle} onChange={e=>setForm({...form,rewardTitle:e.target.value})} className="border rounded-lg p-2"/><input placeholder="قيمة المكافأة" value={form.rewardValue} onChange={e=>setForm({...form,rewardValue:e.target.value})} className="border rounded-lg p-2"/><input required type="url" placeholder="رابط الاختبار الخاص" value={form.testUrl} onChange={e=>setForm({...form,testUrl:e.target.value})} className="border rounded-lg p-2"/><input placeholder="رابط الأيقونة" value={form.iconUrl} onChange={e=>setForm({...form,iconUrl:e.target.value})} className="border rounded-lg p-2"/>
      <input type="number" min="1" value={form.durationDays} onChange={e=>setForm({...form,durationDays:Number(e.target.value)})} className="border rounded-lg p-2"/><input type="number" min="1" value={form.requiredTestersCount} onChange={e=>setForm({...form,requiredTestersCount:Number(e.target.value)})} className="border rounded-lg p-2"/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value as AppCampaign['status']})} className="border rounded-lg p-2">{['draft','active','paused','completed'].map(x=><option key={x}>{x}</option>)}</select>
      <textarea placeholder="الوصف الكامل" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="md:col-span-2 border rounded-lg p-2 min-h-24"/><textarea placeholder="تعليمات الاختبار" value={form.testingInstructions} onChange={e=>setForm({...form,testingInstructions:e.target.value})} className="md:col-span-2 border rounded-lg p-2 min-h-24"/><button className="xl:col-span-3 bg-blue-600 text-white rounded-lg p-3 font-bold"><Plus className="inline w-4"/> إنشاء الحملة</button>
    </form></section>
    <section className="border rounded-2xl bg-white p-5"><h2 className="font-black text-lg mb-3">طلبات المطورين</h2>{app.developers.map(d=><div key={d.id} className="border-b py-3 flex flex-col md:flex-row justify-between gap-2"><span><b>{d.name}</b> · {d.email} · {d.companyName} · {d.status}<small className="block text-slate-500">{d.bio || 'لا توجد نبذة'} · {d.submittedAt}</small></span><span className="flex gap-3 text-sm">{d.status==='pending_approval'&&<><button className="text-emerald-700" onClick={()=>app.updateDeveloperStatus(d.id,'approved')}>قبول</button><button className="text-rose-700" onClick={()=>app.updateDeveloperStatus(d.id,'rejected')}>رفض</button></>}{d.status==='approved'&&<><a className="text-blue-700" href={'mailto:'+d.email+'?subject='+encodeURIComponent('تم قبول طلبك كمطور في TestFlow')+'&body='+encodeURIComponent(emailText(d.name))}><Mail className="inline w-4"/> إرسال بريد</a><button onClick={()=>navigator.clipboard.writeText(emailText(d.name)).then(()=>app.showToast('تم نسخ رسالة الموافقة.'))}><Copy className="inline w-4"/> نسخ رسالة</button></>}</span></div>)}</section>
    <section className="border rounded-2xl bg-white p-5"><h2 className="font-black text-lg mb-3">الحملات</h2>{app.campaigns.map(c=><div key={c.id} className="border-b py-3 flex flex-col md:flex-row justify-between gap-2"><span><b>{c.name}</b> · /{c.slug} · {c.platform} · {c.status} · {app.applications.filter(a=>a.campaignId===c.id).length}/{c.requiredTestersCount}</span><span className="flex gap-3 text-sm"><a target="_blank" rel="noreferrer" href={'/campaign/'+c.slug}><ExternalLink className="inline w-4"/> العامة</a><button onClick={()=>setCampaignId(c.id)}><Users className="inline w-4"/> المختبرون</button><button onClick={()=>void app.updateCampaign(c.id,{status:c.status==='active'?'paused':'active'})}>{c.status==='active'?'إيقاف':'تفعيل'}</button><button className="text-rose-700" onClick={()=>void app.removeCampaign(c.id)}><Trash2 className="inline w-4"/> حذف</button></span></div>)}</section>
    <section className="border rounded-2xl bg-white p-5"><h2 className="font-black text-lg mb-3">طلبات المختبرين</h2><div className="flex flex-wrap gap-2 mb-3"><select value={campaignId} onChange={e=>setCampaignId(e.target.value)} className="border rounded p-2"><option value="all">كل الحملات</option>{app.campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="border rounded p-2"><option value="all">كل الحالات</option>{applicationStatuses.map(x=><option key={x}>{x}</option>)}</select><select value={platform} onChange={e=>setPlatform(e.target.value)} className="border rounded p-2"><option value="all">Android/iOS</option><option value="android">Android</option><option value="ios">iOS</option></select><button onClick={()=>csv('full',app.applications)} className="border rounded p-2"><Download className="inline w-4"/> All CSV</button><button onClick={()=>csv('full')} className="border rounded p-2">Filtered CSV</button><button onClick={()=>csv('full',selectedApps)} className="border rounded p-2">Selected CSV</button><button onClick={()=>csv('gmail_only')} className="border rounded p-2">Gmail CSV</button><button onClick={()=>copyTesterGmailsToClipboard(shown).then(n=>app.showToast('تم نسخ '+n+' بريد.'))} className="border rounded p-2"><Copy className="inline w-4"/> نسخ Gmail</button></div><div className="overflow-auto"><table className="w-full text-xs"><thead><tr className="border-b text-right"><th></th><th>الاسم</th><th>Gmail</th><th>Play/Apple</th><th>التطبيق</th><th>الجهاز</th><th>النظام</th><th>الإصدار</th><th>الدولة</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>{shown.map(a=><tr key={a.id} className="border-b"><td><input type="checkbox" checked={selected.includes(a.id)} onChange={()=>setSelected(s=>s.includes(a.id)?s.filter(id=>id!==a.id):[...s,a.id])}/></td><td>{a.testerName}</td><td>{a.testerEmail}</td><td>{a.googlePlayEmail}</td><td>{app.campaigns.find(c=>c.id===a.campaignId)?.name}</td><td>{a.deviceModel}</td><td>{a.osType}</td><td>{a.osVersion}</td><td>{a.testerCountry}</td><td><select value={a.status} onChange={e=>app.updateApplicationStatus(a.id,e.target.value as TesterStatus)}>{applicationStatuses.map(x=><option key={x}>{x}</option>)}</select></td><td>{a.appliedAt}</td></tr>)}</tbody></table></div></section>
  </main>;
};
