import React, { useMemo, useState } from 'react';
import { Copy, Download, ExternalLink, Users } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { useAuth } from '../../context/AuthContext';
import { AppIconImage } from '../common/AppIconImage';
import { copyTesterGmailsToClipboard, exportTestersToCsv } from '../../utils/exportTesters';
import type { TesterStatus } from '../../types';

const states: TesterStatus[] = ['pending','accepted','waiting_for_whitelisting','ready_to_join','joined','active','completed','inactive','rejected'];
export const DeveloperDashboard: React.FC = () => {
  const { user } = useAuth(); const app = useApp(); const [campaignId,setCampaignId] = useState('all'); const [selected,setSelected] = useState<string[]>([]);
  const campaigns = app.campaigns.filter(c=>c.developerId===user?.uid); const applications = app.applications.filter(a=>campaignId==='all'||a.campaignId===campaignId); const pending=applications.filter(a=>a.status==='pending').length;
  const selectedApps = applications.filter(a=>selected.includes(a.id));
  const exportList=(mode:'full'|'gmail_only', list=applications)=>list.length&&exportTestersToCsv({applications:list,campaigns,mode});
  return <main className="max-w-7xl mx-auto p-4 sm:p-6 space-y-6" dir="rtl">
    <header className="rounded-2xl bg-blue-700 text-white p-6"><h1 className="text-2xl font-black">لوحة المطور</h1><p className="text-blue-100">تظهر هنا حملاتك ومختبرو حملاتك فقط.</p></header>
    <div className="grid grid-cols-2 lg:grid-cols-6 gap-3">{[['حملاتي',campaigns.length],['النشطة',campaigns.filter(c=>c.status==='active').length],['إجمالي المختبرين',applications.length],['المعلقة',pending],['المقبولة',applications.filter(a=>a.status==='accepted').length],['المكتملة',applications.filter(a=>a.status==='completed').length]].map(x=><div key={String(x[0])} className="border rounded-xl bg-white p-4"><small>{x[0]}</small><b className="block text-xl">{x[1]}</b></div>)}</div>
    <section className="border rounded-2xl bg-white p-5"><h2 className="font-black text-lg mb-3">حملاتي</h2>{campaigns.map(c=><div key={c.id} className="border-b py-3 flex flex-col md:flex-row justify-between gap-2"><div className="flex items-center gap-3"><AppIconImage src={c.iconUrl} appName={c.name} category={c.category} className="h-11 w-11 rounded-xl"/><span><b>{c.name}</b> · /{c.slug} · {c.platform} · {c.testType} · {c.status} · {app.applications.filter(a=>a.campaignId===c.id).length}/{c.requiredTestersCount} · {c.durationDays} يوم</span></div><span className="flex gap-3 text-sm"><a target="_blank" rel="noreferrer" href={'/campaign/'+c.slug}><ExternalLink className="inline w-4"/> العامة</a><button onClick={()=>setCampaignId(c.id)}><Users className="inline w-4"/> المختبرون</button><button onClick={()=>void app.updateCampaign(c.id,{status:c.status==='active'?'paused':'active'})}>{c.status==='active'?'إيقاف':'تفعيل'}</button></span></div>)}</section>
    <section className="border rounded-2xl bg-white p-5"><h2 className="font-black text-lg mb-3">مختبرو الحملة</h2><div className="flex flex-wrap gap-2 mb-3"><select value={campaignId} onChange={e=>setCampaignId(e.target.value)} className="border rounded p-2"><option value="all">كل حملاتي</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button onClick={()=>exportList('full')} className="border rounded p-2"><Download className="inline w-4"/> CSV</button><button onClick={()=>exportList('gmail_only')} className="border rounded p-2">Gmail CSV</button><button onClick={()=>exportList('full',selectedApps)} className="border rounded p-2">Selected</button><button onClick={()=>copyTesterGmailsToClipboard(applications).then(n=>app.showToast('تم نسخ '+n+' بريد.'))} className="border rounded p-2"><Copy className="inline w-4"/> نسخ Gmail</button></div><div className="overflow-auto"><table className="w-full text-xs"><thead><tr className="border-b text-right"><th></th><th>الاسم</th><th>Gmail</th><th>Play/Apple</th><th>الجهاز</th><th>النظام</th><th>الإصدار</th><th>الدولة</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>{applications.map(a=><tr key={a.id} className="border-b"><td><input type="checkbox" checked={selected.includes(a.id)} onChange={()=>setSelected(s=>s.includes(a.id)?s.filter(id=>id!==a.id):[...s,a.id])}/></td><td>{a.testerName}</td><td>{a.testerEmail}</td><td>{a.googlePlayEmail}</td><td>{a.deviceModel}</td><td>{a.osType}</td><td>{a.osVersion}</td><td>{a.testerCountry}</td><td><select value={a.status} onChange={e=>app.updateApplicationStatus(a.id,e.target.value as TesterStatus)}>{states.map(x=><option key={x}>{x}</option>)}</select></td><td>{a.appliedAt}</td></tr>)}</tbody></table></div></section>
  </main>;
};
